[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
itertools = "0.13.0"
ndarray = "0.16.1"
nom = "7.1.3"
petgraph = "0.6.5"
rayon = "1.10.0"
regex = "1.11.1"
